version: '3.9'
services:
  postgres:
    image: 'postgres:14'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
